add matrix

diff --git a/.github/workflows/prefix.yml b/.github/workflows/prefix.yml
--- a/.github/workflows/prefix.yml
+++ b/.github/workflows/prefix.yml
@@ -8,6 +8,12 @@ on:
 jobs:
   prefix-symbols:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        target:
+          - stable
+          - armv7-linux-androideabi
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
@@ -18,20 +24,36 @@ jobs:
           cargo add boring-sys2 --path ../boring-sys/
           cargo add openssl-sys -F vendored
           echo "fn main() {boring_sys2::init(); openssl_sys::init();}" > src/main.rs
+      - name: Prepare Android toolchain
+        if: matrix.target == 'armv7-linux-androideabi'
+        run: |
+          rustup target add ${{ matrix.target }}
+          cargo install cargo-ndk
       - name: Build without prefixing
+        if: matrix.target == 'stable'
         run: |
           if ! cargo build 2>&1 | grep "rust-lld: error: duplicate symbol"; then
             echo "Build without prefixing succeeded, should fail.";
             exit 1;
           fi
-      - name: Build with prefixing
+      - name: Android build without prefixing
+        if: matrix.target == 'armv7-linux-androideabi'
+        run: |
+          if ! cargo ndk -t ${{ matrix.target }} build 2>&1 | grep "rust-lld: error: duplicate symbol"; then
+            echo "Build without prefixing succeeded, should fail.";
+            exit 1;
+          fi
+      - name: Add prefix-symbols feature
         run: |
           cd brssl2-prefix
           cargo add boring-sys2 --path ../boring-sys/ -F prefix-symbols
+      - name: Build with prefixing
+        if: matrix.target == 'armv7-linux-androideabi'
+        run: |
+          pwd
           cargo build
       - name: Android build with prefixing
+        if: matrix.target == 'armv7-linux-androideabi'
         run: |
-          rustup target add armv7-linux-androideabi
-          cargo install cargo-ndk
-          cd brssl2-prefix
-          cargo ndk -t armv7-linux-androideabi build
+          pwd
+          cargo ndk -t ${{ matrix.target }} build
